---
name: Test on Multiple OS

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

permissions: {}

jobs:
  test_ubuntu:
    name: Test on Ubuntu
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Python scripts on Linux
        run: |
          for script in scripts/*.py; do
            echo "Running $script"
            python "$script" --records 5
          done
        shell: bash

  test_windows:
    name: Test on Windows
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Python scripts on Windows
        run: |
          Get-ChildItem scripts\*.py | ForEach-Object {
            echo "Running $_"
            python $_ --records 5
          }
        shell: pwsh

  test_macos:
    name: Test on macOS
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Python scripts on macOS
        run: |
          for script in scripts/*.py; do
            echo "Running $script"
            python "$script" --records 5
          done
        shell: bash
